### ISSUE TITLE
Where should I put the unpacked files?

### ISSUE THREAD

**Issue by tywong7** [L-Leite/cso2-launcher#100]
Hi, 
I am using the version: cso2_launcher-0.6.0-win64_clang with the command:
`launcher.exe -masterip 127.0.0.1 -masterport 30001 -unpackedfiles`

Also, I use UnCSO2-2.0.7 to unpack everything inside /Data directory. Now the directory looks like this:

![image](https://user-images.githubusercontent.com/5148816/100771337-4a581980-3439-11eb-91aa-93687478f2d7.png)

![image](https://user-images.githubusercontent.com/5148816/100771393-593ecc00-3439-11eb-8b4a-015548df3a66.png)

However, when I run the launcher, the following error shows:
![image](https://user-images.githubusercontent.com/5148816/100771500-71aee680-3439-11eb-82ba-ea9c529c9af3.png)

Am I putting those unpacked files in a wrong directory? Thank you very much.

**Comment by izmoxkawaii** [comment]
@L-Leite

**Comment by izmoxkawaii** [comment]
try 
 /data/cstrike/custon
 /data/cstrike/custom

**Comment by L-Leite** [comment]
the 0.6.0 launcher is old and doesn't support unpacked files
try using this launcher: https://ci.appveyor.com/api/buildjobs/d8krbqyxt589nngk/artifacts/build%2Fcso2_launcher-0.6.0-win64_msvc.7z

**Comment by tywong7** [comment]
Thank you guys. It finally works after using the 

> the 0.6.0 launcher is old and it doesn't support unpacked files
> try using this launcher: https://ci.appveyor.com/api/buildjobs/d8krbqyxt589nngk/artifacts/build%2Fcso2_launcher-0.6.0-win64_msvc.7z

Thank you guys. It finally works after using this launcher.

**Comment by IGNRexI** [comment]
> 0.6.0 başlatıcı eski ve paketlenmemiş dosyaları desteklemiyor bu başlatıcıyı kullanmayı deneyin: https://ci.appveyor.com/api/buildjobs/d8krbqyxt589nngk/artifacts/build%2Fcso2_launcher-0.6.0-win64_msvc.7z

Can you share the source codes?

**Comment by Yoshzy** [comment]
Link down :/
@L-Leite give laucher version to accept custom unpacked files broh, i need parse to english langue to play with my friends
