### ISSUE TITLE
Display ping

### ISSUE THREAD

**Issue by organnerx** [L-Leite/cso2-launcher#101]
Hello. If you play Chinese version of the game you can display your ping with "cl_showfps 1" command, however this feature is not available in Korean version of the game. Maybe you can check how Chinese version is displaying the ping and implement that to Korean version too.
![CounterStrikeOnline2 2018-03-23 14-00-43-378](https://user-images.githubusercontent.com/45734900/101978732-216d2b00-3c68-11eb-90d9-86c537292af6.jpg)

**Comment by izmoxkawaii** [comment]
Is this ping value cso2_ui.gfx not included?

**Comment by izmoxkawaii** [comment]
how can we do that? Do you have a client? @organnerx
