### ISSUE TITLE
the latest version of the launcher and its console and the lack of a command 

### ISSUE THREAD

**Issue by ADVABonnie** [L-Leite/cso2-launcher#102]
Hello @L-Leite  why don't 2 important commands work -decryptedfiles-enablecustom for the latest version of the launcher and the game crashes when you enter I do not know but this problem is only mine can you help or fix this problem with the crash of the launcher and 2 commands -decryptedfiles-enablecustom I'll be glad to hear it).

**Comment by L-Leite** [comment]
what's your launcher's version?

**Comment by ADVABonnie** [comment]
0.6.0 it doesn't work there 
i can give a screenshot
![cso2_0377](https://user-images.githubusercontent.com/69756761/103100923-0619fc80-4626-11eb-9912-b5e95529c852.jpg)

**Comment by ADVABonnie** [comment]
the game crashes when I log into my account

**Comment by ADVABonnie** [comment]
will be able to solve the problem, these commands -decryptedfiles-enablecustom they just don't work

**Comment by izmoxkawaii** [comment]
+++++++++++
