### ISSUE TITLE
CSO2 UI Console :)

### ISSUE THREAD

**Issue by ADVABonnie** [L-Leite/cso2-launcher#105]
Hi @L-Leite are there any commands in the console game, for example, a change of position, I saw that there was 1 change of position and this is the chat position in the game, is it possible to find out whether it is possible to change all the position of the radar, the position of the cartridges and the change of weapons, and so on, all the commands as the console speaks, there are only 48 of them here so many or there are even more teams so that you can watch everything and every thin and all his shift and not just chat
![cso2_0736](https://user-images.githubusercontent.com/69756761/103386146-7802b200-4b0e-11eb-9235-d04234e8e86f.jpg)

**Comment by Vad1mCSO2** [comment]
https://github.com/L-Leite/cso2-launcher/issues/94

**Comment by ADVABonnie** [comment]
> #94

vadim you are not L-Leite no delete your stupid message
