### ISSUE TITLE
-unpackedfiles deosn't work or i am doing something wrong idk

### ISSUE THREAD

**Issue by lostfxo** [L-Leite/cso2-launcher#110]
i extracted pkg's with uncso2 and used -unpackedfiles but it gives me "failed to init required launcher systems".

**Comment by IGNRexI** [comment]
+

**Comment by IGNRexI** [comment]
+++++++++++++

**Comment by lostfxo** [comment]
they work at latest version without problem but textures doesn't work i fixed it by only unpacking materials folder with https://github.com/L-Leite/UnCSO2/releases/tag/1.4.6 version of uncso2 and i unpacked rest with the latest version its just my problem sorry :/
