### ISSUE TITLE
When changing the game language. change the sound file.

### ISSUE THREAD

**Issue by IGNRexI** [L-Leite/cso2-launcher#111]
The user who chooses his language may want to hear voices in his own language. Customize the audio folder for multiple languages ​​to support it!

oss << "sound/_" << szLanguage << "./";

![Untitled](https://user-images.githubusercontent.com/36341134/147863560-90471c86-c3bc-487c-bc73-d6c1b23c8adf.png)

**Comment by UmutLykia** [comment]
+1 ref

**Comment by IGNRexI** [comment]
all file types are encoded by language++ <3
