### ISSUE TITLE
Game crash in Linux running under WINE

### ISSUE THREAD

**Issue by Corrupt-Specturion** [L-Leite/cso2-launcher#115]
I am trying to run the game under Linux Mint Mate 20.2, with wine-stable 7.0 (running in Windows 10 mode), but it crashes after a certain amount of time, depending on how long the main menu is in focus. The crash seems to be prevented by staying in the options menu, and logging in immediately results in a crash, even if authentication info is specified in the flags.
Has the game been successfully tested under any version of WINE? If so, which version last tested was working?
I have not built the program for my system, instead I downloaded Release 0.6.0 so this may be one of the issues. Although, it does not seem to give build instructions for Linux, only Windows.
I also noticed that it threw `"GL_OUT_OF_MEMORY error generated. Failed to allocate CPU address space mapping for buffer object (consider building 64-bit app).".`, so it may be that the application is 32-bit as well.
[Here is the log from the terminal session.](https://github.com/L-Leite/cso2-launcher/files/8664623/log_cso2.txt)

**Comment by ADVAFTB** [comment]
try the old version of CSO2 https://drive.google.com/file/d/1qNhSs74HF3TMFvKzm4LynxRb6UBwRRQ7/view (Password OlD) it works or run the game on proton-steam (New Client 2018) but 1 problem is radmin vpn it does not work not on wine and not on proton

**Comment by Corrupt-Specturion** [comment]
I was trying to avoid using Radmin or the Russian fork because

1. Can't run Radmin on Linux

2. Once they inevitably shutter the service, all my stuff will be deleted and all my progress will be lost. With a self-hosted server, I could save my progress forever, modify it as I please, and not have to rely on a 3rd party service.

It would be helpful if the fork team open-sourced their modifications, but they've said they aren't going to do that.

Speaking of the Russian fork, does anyone know if I can use their English localization files with this base client once I get it working, and how? I tried the stuff in #113 and `-unpackedfiles` but they didn't work.

**Comment by Corrupt-Specturion** [comment]
Using wine-staging 7.22 in Windows 7 mode, the game seems to only crash upon dismissing the server connection error message, but it is laggy when graphics settings are high. I cannot test further yet since the test server is closed, I have not yet gotten a server working on my Raspberry Pi, and I do not know of anyone currently hosting a server.

Google Translate's camera mode seems enough to get by for now.

**Comment by Corrupt-Specturion** [comment]
I have set up a server on my Linux laptop, and CSO2 almost works. At seemingly random, it crashes to desktop with memory allocation errors. I’ve tried giving it more VRAM, using wine64, and disconnecting my second monitor, but those make little difference. Unfortunately, it seems I will have to use Windows for the time being.

**Comment by Corrupt-Specturion** [comment]
[Works with Proton 5.13-6.](https://youtu.be/_Z5soy16eHE)

I know I'm not supposed to run non-Steam games through Proton, but I don't really want to mess with Lutris or downgrading WINE .

[According to this thread, WINE 6.3 (and presumably above) have an issue with memory allocation](https://bugs.freebsd.org/bugzilla//show_bug.cgi?id=255336), so I tried the next Proton version down on Steam.
