### ISSUE TITLE
+exec "somefile.cfg"

### ISSUE THREAD

**Issue by qiangqiang101** [L-Leite/cso2-launcher#31]
request exec command

**Comment by Ochii** [comment]
This should be available once we get the client to load unpacked and decrypted files.

Right now the unpacker I built has a bug (Ochii/UnCSO2#3) when decrypting files. It's also really slow

**Comment by qiangqiang101** [comment]
@Ochii it's not just bug, it crashed upon browsing the Data folder

**Comment by GEEKiDoS** [comment]
> @Ochii it's not just bug, it crashed upon browsing the Data folder

Try to compile from soruce, The code in master branch should fixed crash on nexon files.
If you dont have compiler, Just download this old release: https://github.com/Ochii/UnCSO2/releases/tag/1.4.3

**Comment by Ochii** [comment]
Sorry, I haven't upload an updated version of it. Give me a moment and I'll get it ready

**Comment by GEEKiDoS** [comment]
> Sorry, I haven't upload an updated version of it. Give me a moment and I'll get it ready

https://github.com/Ochii/UnCSO2/issues/4 Should same as https://github.com/Ochii/UnCSO2/issues/2 and this

**Comment by Ochii** [comment]
@qiangqiang101 check out [version 1.4.5](https://github.com/Ochii/UnCSO2/releases/tag/1.4.5)

**Comment by L-Leite** [comment]
you can use unpacked game files with [version 0.6.0](https://github.com/L-Leite/cso2-launcher/releases/tag/Version-0.6.0), and you should be able to put your custom configs in there too
