### ISSUE TITLE
Cannot use decrypted custom files

### ISSUE THREAD

**Issue by Edenia3** [L-Leite/cso2-launcher#35]
No bots with latest launcher

**Comment by Edenia3** [comment]
I noticed the decrypted custom files doesn't work correctly now.
In previous release was able to change bot profile and everything worked just fine, but now after changing or replacing this file - bot can't join the game.

Edit: by default everything works fine.

**Comment by GEEKiDoS** [comment]
Using decrypted files in custom works fine for me

Is there any example bot profile that I can test with?

![qq 20190218061431](https://user-images.githubusercontent.com/14933408/52920159-9e693b00-3344-11e9-988d-5f926fb9e359.jpg)

**Comment by Edenia3** [comment]
Any file in custom folder not working.
Game crash or missing images/translation.
But everything works fine with launcher version 0.2.2

**Comment by enesvtn** [comment]
I can't access the language folder in Korean I don't want to change how?

**Comment by Gazyi** [comment]
Everyone who expects crashes since 0.3.3 and have localization: move localization file from "custom" folder to "Data\cstrike\resource\".

**Comment by L-Leite** [comment]
you can now use unpacked files with [version 0.6.0](https://github.com/L-Leite/cso2-launcher/releases/tag/Version-0.6.0)
