### ISSUE TITLE
Can't Load File-ui/cso2_ui.gfx 

### ISSUE THREAD

**Issue by darknessmaddog** [L-Leite/cso2-launcher#39]
My friend so many
And they ask
Can't Load File-ui/cso2_ui.gfx 
How to fix it?

**Comment by Edenia3** [comment]
-decryptedfiles -enablecustom currently broken, say them to remove custom folder

**Comment by GEEKiDoS** [comment]
https://github.com/Ochii/cso2-launcher/issues/21#issuecomment-462324503
