### ISSUE TITLE
Back button missing

### ISSUE THREAD

**Issue by xRiseless** [L-Leite/cso2-launcher#53]
Back button disappear sometimes. And you need to press ESC to left room or server. This bug appears only on 0.4.0+ versions

**Comment by Riseless** [comment]
Bug appears when you use -username and -password arg. If you input this manually - all works normally

**Comment by Ochii** [comment]
@GEEKiDoS do you know why this happens?

**Comment by GEEKiDoS** [comment]
> @GEEKiDoS do you know why this happens?

I guess it's a bug from nexon since the back and home displayed in the login screen.
