### ISSUE TITLE
I Need 24407 Launcher

### ISSUE THREAD

**Issue by coolbar1993** [L-Leite/cso2-launcher#62]
Dear Ochii:
請問，可以製作台服 24407 版的啟動器嗎？
台服的無線電語音有多國語音。

Can you make a launcher for Taiwanese 24407 version ?
The Taiwanese 24407 version radio voice has multi-national voice.

**Comment by dounai2333** [comment]
https://github.com/Ochii/UnCSO2
提取台湾版本的音频文件，并将其放置在custom文件夹内，一个很简单的实现方法
