### ISSUE TITLE
Korean name break problem

### ISSUE THREAD

**Issue by cso2** [L-Leite/cso2-launcher#67]
The database is stored as the Korean language is, but the Korean language is broken when you log in to the launcher.

**Comment by DebugBios** [comment]
![cso2_0000](https://user-images.githubusercontent.com/44349391/58690745-3c998200-83c5-11e9-802d-23176d8601b7.jpg)
![cso2_0001](https://user-images.githubusercontent.com/44349391/58690746-3d321880-83c5-11e9-88ba-5380f1b22eef.jpg)
