### ISSUE TITLE
Imgui will cause game problems

### ISSUE THREAD

**Issue by dounai2333** [L-Leite/cso2-launcher#68]
**they comes from other players, I have not been tested it in detail, most of the following are "conjectures" or "not tested in detail"**

most of the time, the console of imgui works fine, but in a few cases, it will cause network problems or game problems in the game, and may need to restart game to solve problem, here are some known bugs from other players or from me:
1. if you open the console in a room and someone or you clicked the start, game will not start after the countdown over, and the game will no longer can get server's packet.
2. if you open the console while reading the map, and keep it open until you enter the game, you won't be able to use it to do anything unless you quit the room. (the same applies to the case where the game start with "map cs_assault")
3. when you host a game, if you use the console for any reason, no any player can join your game anymore and will be prompted with "Invalid Connection Method". who joined before you use the console can still play normally, when he exited the room and try to rejoin, he will not prompt "Invalid Connection Method".

in the client version that does not use imgui, these problems does not happen, these problems are all comes after using the new console.

**Comment by L-Leite** [comment]
imgui got removed in commit bfa4047
