### ISSUE TITLE
How do I edit cso2_ui.gfx?

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-launcher#73]
How do I edit cso2_ui.gfx?
and

![Ekran Alıntısı](https://user-images.githubusercontent.com/36341134/65594190-eb785400-df9a-11e9-8f8d-3f3767df27d9.PNG)

How do I edit

**Comment by L-Leite** [comment]
You can try [JPEXS Free Flash Decompiler](https://github.com/jindrapetrik/jpexs-decompiler/releases/tag/version11.2.0), it reads the .gfx files pretty well.

I didn't try to edit them though.

**Comment by felixabi** [comment]
Thanks <3
