### ISSUE TITLE
Allow to change notice banners

### ISSUE THREAD

**Issue by IGNRexI** [L-Leite/cso2-launcher#74]
Do you have any idea how I can remove these pictures? or how do I edit it?

![Adsız](https://user-images.githubusercontent.com/36341134/65616806-5722e700-dfc4-11e9-9d4e-395968b79ff9.png)

**Comment by felixabi** [comment]
I searched but could not find

**Comment by L-Leite** [comment]
Those banners are retrieved from http://s.nx.com/s2/game/CSO2/notice/

For example: the first notice is http://s.nx.com/s2/game/CSO2/notice/00.jpg

I think you can either patch the client's code to load your own notices, or you redirect s.nx.com to localhost and serve your own images.

I might implement the first option some day, don't know when

**Comment by felixabi** [comment]
I don't know where it is in which file can I find?

**Comment by L-Leite** [comment]
They're downloaded remotely, you can't find them in your disk

**Comment by felixabi** [comment]
isn't there a way to change that?

**Comment by L-Leite** [comment]
I think you can either patch the game to load your images or you redirect s.nx.com to localhost and serve your own images there

**Comment by felixabi** [comment]
just want to put gun banners for the game

**Comment by felixabi** [comment]
and education posters

**Comment by felixabi** [comment]
by the way
I'm making a map for cso2 but what can I do to run it in cso2?
Maps of Zombies

**Comment by L-Leite** [comment]
I'm not sure, but I think you would need custom Hammer binaries with reversed engine structures.

If you want to keep discussing about this, please open a new issue

**Comment by felixabi** [comment]
okey <3

**Comment by GEEKiDoS** [comment]
I have been written some ugly code for this few month ago
https://github.com/GEEKiDoS/cso2-launcher/blob/modularizated/src/Plugins/Login/PatchCSO2_Engine.cpp#L109
https://github.com/GEEKiDoS/cso2-launcher/blob/modularizated/src/Plugins/Login/stdafx.h#L21

**Comment by felixabi** [comment]
@GEEKiDoS can you help me.
original cso2 launcher works in visual studio 2019 > https://github.com/L-Leite/cso2-launcher


![Ekran Alıntısı](https://user-images.githubusercontent.com/36341134/67477713-5339c180-f663-11e9-96ee-c065f1803f6d.PNG)

https://github.com/GEEKiDoS/cso2-launcher

**Comment by L-Leite** [comment]
Good work @GEEKiDoS, if you can open a pull request with your patch I will merge it

A 22 de outubro de 2019 12:34:20 WEST, GEEKiDoS <notifications@github.com> escreveu:

**Comment by felixabi** [comment]
@GEEKiDoS  @L-Leite  : when will you arrange to change banners?

**Comment by L-Leite** [comment]
I'm not sure
I also don't know where the banner's host URL will be retrieved from.
Maybe from a config file or from the master server host that is already set by the user

**Comment by izmoxkawaii** [comment]
![image](https://user-images.githubusercontent.com/36341134/128266524-1e2675e0-07de-4f2e-88b8-e44ea738a363.png)
package cso2.ui.promotionObjs
I made it by editing .gfx
![image](https://user-images.githubusercontent.com/36341134/128266713-24cdfe38-62f7-4522-90bd-0ad700053a64.png)
