### ISSUE TITLE
.csv do I decrypt passwords?

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-launcher#77]
.csv do I decrypt passwords?

![Ekran Alıntısı](https://user-images.githubusercontent.com/36341134/65818960-6487dd80-e21f-11e9-9c78-7cb3d2ea09b5.PNG)

**Comment by L-Leite** [comment]
I don't understand your question, are you asking how to decrypt .csv files?

**Comment by felixabi** [comment]
yes

**Comment by L-Leite** [comment]
Wait for the next UnCSO2 release

**Comment by L-Leite** [comment]
[Release v2.0.4](https://github.com/L-Leite/UnCSO2/releases/tag/v2.0.4) of UnCSO2 was just published, give it a try
