### ISSUE TITLE
Unable to add custom skins

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-launcher#79]
cso2_item_rev2.csv I'm adding Skin, but it doesn't appear in inventory
For example, I will add a spray, but does not appear

**Comment by felixabi** [comment]
100019,#CSO2_ITEM_NAME_knife_kids_flag,#CSO2_ITEM_DESC_knife_kids_flag,default_knife,kids_flag,item,weapon,knife,2,0,3|53,0,0,0,5,0,0,0,none,none,0,0,,,,0

**Comment by felixabi** [comment]
100019,#CSO2_ITEM_NAME_gr_a_kids_flag,#CSO2_ITEM_DESC_gr_a_kids_flag,gr_a_kids_flag,default,spray,class,spray,11,0,0,0,0,0,5,0,0,0,none,none,0,0,,,,0

**Comment by dounai2333** [comment]
you need to add it to your inventory via [inventory-service](https://github.com/L-Leite/cso2-inventory-service/blob/master/src/entities/defaultitems.ts).
