### ISSUE TITLE
Launcher crash

### ISSUE THREAD

**Issue by yusuflq** [L-Leite/cso2-launcher#88]
Windows Event Viewer:

Incorrect application name: launcher.exe_unknown, version: 0.4.1.0, timestamp: 0x5ed17a47
Bad module name: launcher.exe, version: 0.4.1.0, timestamp: 0x5ed17a47
Exception code: 0xc0000005
Error distance 0x0000000000050b53
Incorrect transaction ID: 0x1898
Application start time: 0x01d635fe68cb681f
Incorrect application path: D:\CSO2\Bin\launcher.exe
Bad module path: D:\CSO2\Bin\launcher.exe
Report ID: 8256ef1b-00dc-44c4-a47a-5355a1124ec7
Bad package full name:
Application ID related to the faulty package:

**Comment by yusuflq** [comment]
I built new, I did everything right, successful, but there is a problem

**Comment by ExplosionMagicMegumin** [comment]
+

**Comment by ExplosionMagicMegumin** [comment]
@L-Leite look at there

**Comment by ExplosionMagicMegumin** [comment]
I'm having the same problem

**Comment by dounai2333** [comment]
any 0.3.0 or newer launcher can not running at Win7, if you encounter such problems on Win7, please use 0.2.2 instead.

**Comment by ExplosionMagicMegumin** [comment]
i already use windows 10 i get the same error

**Comment by ExplosionMagicMegumin** [comment]
I am not using windows 7 and it gives error when I build a new launcher

**Comment by L-Leite** [comment]
@yusuflq @ExplosionMagicMegumin can you try [this build](https://ci.appveyor.com/api/buildjobs/2r1imum82sahh8md/artifacts/build%2Fcso2_launcher-0.4.1-win64_msvc.7z)?

**Comment by ExplosionMagicMegumin** [comment]
It works well. 
where is the source code?

**Comment by YuRaNnNzZZ** [comment]
> where is the source code?

It's literally built from [this commit](https://github.com/L-Leite/cso2-launcher/commit/5d454a2b97bd422af8eba4bdc97bc649bd261dbd):
https://ci.appveyor.com/project/L-Leite/cso2-launcher/branch/master/job/2r1imum82sahh8md

**Comment by ExplosionMagicMegumin** [comment]
I downloaded the latest version again
when you rebuild it, the launcher crashes again.


Errorbundle1877964671019050001,type4
EventName:APPCRASH
Answer:Notavailable
CabinID:0

Problemsignature:
P1:launcher.exe_unknown
P2:0.4.1.0
P3:5ee7586c
P4:launcher.exe
P5:0.4.1.0
P6:5ee7586c
P7:c0000005
P8:0000000000050d73
P9:
P10:

Attachedfiles:
C:\ProgramData\Microsoft\Windows\WR\Temp\wer509c.tmp.dmp
C:\ProgramData\Microsoft\Windows\WR\Temp\wer510b.tmp.werınternalmetadata.xml
C:\ProgramData\Microsoft\Windows\WR\Temp\wer513b.tmp.xml
C:\ProgramData\Microsoft\Windows\WR\Temp\wer514c.tmp.csv
C:\ProgramData\Microsoft\Windows\WR\Temp\wer517c.tmp.txt

Thesefilescanbefoundhere:
C:\ProgramData\Microsoft\Windows\WR\reportarchivto\appcrash_launcher.exe_unk_cd6c11b572ccf5e2db9b5e8ddc06c8c8d1c46_e3ec412f_6208a751-5e87-4736-88cf-252f354bf20b

Analysisicon:
Recheckforsolution:0
ReportID:6c027af3-fb97-4189-93aa-5b34d5b8128b
ReportStatus:268435456
Hashbunch:aad80643e4934910ba0fdeeb1cd2e411
CabinGuid:0

@L-Leite  @YuRaNnNzZZ  @dounai2333

**Comment by L-Leite** [comment]
which compiler are you using?
