### ISSUE TITLE
Create tool for the maps conversion

### ISSUE THREAD

**Issue by organnerx** [L-Leite/cso2-launcher#90]
It could be nice to play a previous version of the game when engine was not updated yet. Can you change offsets in the launcher to make it launch the older version of the game?
Pros:
1) Zombie Commander should work.
2) **Players-made maps** and **maps from CSS** should work. Also bigcity_pvp map should work.
3) Maps that were remade/added after engine updated should be easily converted to old engine (CSS engine) version.

Cons:
1) Latest gamemodes will not work.
2) Latest weapons will not work.
3) Shader of the old engine looks a bit outdated.

Summary:
1) We will **loose some content** but that will allow us to play **custom maps** if we want to, since there are no tools to convert CSS maps to the current CSO2 engine version.
2) Luís Leite, please consider making the launcher for an older version of the game, or create a tool to convert maps to current CSO2 engine. Players need it.

**Comment by 5SAYMON7** [comment]
custom maps!

**Comment by 1DSBM1I1SMY1LIFE0** [comment]
+

**Comment by 1DSBM1I1SMY1LIFE0** [comment]
yes please

**Comment by BunseiWZ** [comment]
I think I can try it.

**Comment by BunseiWZ** [comment]
I think it can be done!

**Comment by xRiseless** [comment]
I think it will be cool!

**Comment by pepeftog** [comment]
would be nice, yeah

**Comment by UnionOfUniverses** [comment]
Good idea, hope it will be.

**Comment by xxxmenjaZastavilyxxx** [comment]
nice

**Comment by NazguuulL** [comment]
yes please!

**Comment by ADVABonnie** [comment]
it will be good that we will play the old version of the game

- 
- 

- 

> ### _**``**_

**Comment by roboral** [comment]
Nice

**Comment by Valen7789** [comment]
👌🏻

**Comment by ADVABonnie** [comment]
👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻👌🏻

**Comment by ADVABonnie** [comment]
please make the launcher or the program to convert the cards or create them for us, it should be at least good will in BIGCITY to play here at the beginners a lot and the regime does not recover if the right engine and there will be a lot of players if there is a option from the old version to build easy to play on maps from players witch do

**Comment by ADVABonnie** [comment]
Variation. It will be great for us

**Comment by cso2** [comment]
I wish I could make a new mode and map.

But I think the priority is much lower than other functions.

**Comment by cso2** [comment]
I wish I could play a new mode and map.

But I think the priority is much lower than other functions.


#41

**Comment by L-Leite** [comment]
@organnerx can you send me a copy of an old version of the game?

in the future I would like to make the latest client capable of loading old maps or create a tool to convert the map format from CSS to CSO2

**Comment by pepeftog** [comment]
and what about z commander

**Comment by pepeftog** [comment]
?

**Comment by organnerx** [comment]
@L-Leite thank you for noticing the game community. I have a couple of different versions. Currenly we are looking for the latest available version before engine update. Right now I have February 2017 version while engine update was made in June 2017. I'll let you know in a few days about the search results.

It is a great idea to patch the client to load old maps or to make a tool for maps conversion in future. Believe me, players played the same maps for 999 times already and new maps will work like a breath of fresh air for the game.

**Comment by JackyNKL** [comment]
> @organnerx can you send me a copy of an old version of the game?
> 
> I will make the launcher look for the addresses to be patched through byte signatures
> In the future I would like to make the latest client capable of loading old maps or create a tool to convert the map format from CSS to CSO2

I have tried to convert CSS map to CSO2, the map binary structure can be recognized by the engine but it always crashed after R_LoadWorldGeometry() inside R_LevelInit() in the engine. However, if I convert the map of CSO2 to CSS and back to CSO2 format, it has no problem despite some lighting break. Hope this information can help you.

**Comment by L-Leite** [comment]
I pushed commit 1b30e74 you can get a build [here](https://github.com/L-Leite/cso2-launcher/releases/tag/0.5.0).

The launcher will now try to find and patch the addresses dynamically, so you should be able to play with different clients.
I tested with Korea's v24406 client and the Chinese version from 21 february 2017 sent by organnerx.

**Comment by organnerx** [comment]
@L-Leite thanks, I was able to run the game with the new launcher, but it does not load "custom" (-enablecustom) and "Data/cstrike" (-decryptedfiles) folders in 2017 version of the game. I cannot check if CSS maps can be played without working custom folder.

**Comment by L-Leite** [comment]
@organnerx can you test this build? [build-rel.zip](https://github.com/L-Leite/cso2-launcher/files/5119963/build-rel.zip)

**Comment by Kawaii-Maou-Sama** [comment]
I tested -lang not working

**Comment by L-Leite** [comment]
@Kawaii-Maou-Sama can you try this build? 
[build-rel.zip](https://github.com/L-Leite/cso2-launcher/files/5120153/build-rel.zip)

**Comment by Kawaii-Maou-Sama** [comment]
working .. successful

**Comment by Kawaii-Maou-Sama** [comment]
![image](https://user-images.githubusercontent.com/36341134/91095655-66436680-e665-11ea-9650-74f2c6a3466a.png)
really good beautiful

**Comment by Kawaii-Maou-Sama** [comment]
![image](https://user-images.githubusercontent.com/36341134/91095932-d4882900-e665-11ea-82db-bfde2f414ec0.png)
Why is the server in the clan list?

**Comment by ADVABonnie** [comment]
I don't have any concepts probably it was in the game just no one remembers although if I say so the Organner gave me the old interface but it was different in a different way but there were bugs like opening cases and so on

**Comment by ADVABonnie** [comment]
Organner strange that will if maps insert in data and custom that will in old game try potestit and for 1 will make an important chip and will send in discord ) 

- 

1. 

**(Soryan for 2 that I wrote OK)**

**Comment by Kawaii-Maou-Sama** [comment]
![image](https://user-images.githubusercontent.com/36341134/91098371-03080300-e66a-11ea-956d-9c79d42ec719.png)
 CLAN?
Why is the server in the clan list?

**Comment by ADVABonnie** [comment]
L-Leite Help me I have an error it requires 1 file so that it can run the game VCRUNTIME140.dll can you help me or tell me how to fix it (

**Comment by L-Leite** [comment]
you need the Visual Studio C++ Redist, you can get it at https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by ADVABonnie** [comment]
Thanks

**Comment by ADVABonnie** [comment]
L-Leite Sorry but it didn't help I'd rather manually find the file myself

**Comment by Kawaii-Maou-Sama** [comment]
@ADVABonnie 
try https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by ADVABonnie** [comment]
![cso2_0392](https://user-images.githubusercontent.com/69756761/91107232-749d7c80-e67d-11ea-9bac-ab1000c1277c.jpg)
 L-Lete how do I connect to my server if it doesn't work( although it is enabled

**Comment by ADVABonnie** [comment]
> @ADVABonnie
> попробуй https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

Thank you but I already downloaded the dll Manually

**Comment by Kawaii-Maou-Sama** [comment]
@L-Leite In 2 minutes or 3 minutes the game shuts down by itself

**Comment by organnerx** [comment]
@L-Leite sorry for being too late. Is launcher in Releases already updated to use custom and decrypted, or I need to download the file you sent in comments? I'm gonna test everything properly in 10 hours and report back to you

**Comment by ADVABonnie** [comment]
@L-Leite so**rry but you have problems that I found these are commands they don't work console doesn't work all commands don't work I want to run custom maps of course well you of course fix it please and it's just not convenient to play without those commands that don't work at all update the launcher version for the console just the console doesn't work**

**Comment by Valen7789** [comment]
@L-Leite I donwloaded the latest version of the launcher. The custom folder works very nice, but the console commands doesn't work. I tried to put any command like `cl_showfps` `cl_righthand` `mat_setvideomode` `net_graph` etc etc and NONE works

**Comment by Kawaii-Maou-Sama** [comment]
and maps command not working

**Comment by L-Leite** [comment]
@ADVABonnie @Valen7789 @Kawaii-Maou-Sama try again with [release 0.5.2](https://github.com/L-Leite/cso2-launcher/releases/tag/0.5.2)

**Comment by ADVABonnie** [comment]
@L-Leite  sorry, but there are errors in your launcher versions that even now exist
can you take the version I gave you and fix the code for this version without creating any errors there just all the launcher versions have errors just take your time the launcher version and carefully try to fix the launcher version some commands don't work in the launcher for version 5.3 or another try to fix the launcher code and enter 2017 which should work without crashes and errors
![cso2_0443](https://user-images.githubusercontent.com/69756761/91221350-34de9f80-e726-11ea-8b5a-46b3c8d72ed0.jpg)

and Yes here I am about this or was it in the game


1. https://drive.google.com/file/d/1k_-9mxAlGLWUcAU0RlRLME6evCm9AW6T/view

**Comment by organnerx** [comment]
> In the future I would like to make the latest client capable of loading old maps or create a tool to convert the map format from CSS to CSO2

@L-Leite I have tested 2017 version if it can load the CSS maps. It cannot do it too like a 2018 version. Engine on both game versions will stuck on 'Bsp Version' or on 'Funny lump size'.
About your solution in the future: For various reasons covertion tool will be better than patching the game with the launcher. A message from JackyNKL should be useful in making convertion tool, and it is a really interesting fact that the map can be converted from cso2 to css and back:
> I have tried to convert CSS map to CSO2, the map binary structure can be recognized by the engine but it always crashed after R_LoadWorldGeometry() inside R_LevelInit() in the engine. However, if I convert the map of CSO2 to CSS and back to CSO2 format, it has no problem despite some lighting break.

We all hope that you will be able to understand the map reading procedure and to create a convertion tool for our lovely game in future ;)

**Comment by KouKouChan** [comment]
@L-Leite  @organnerx      I hope these can be helpful for you . Here is a 20170510 version of chinese client, and 0.5.2 launcher works good
[20170510](https://drive.google.com/file/d/16v5-_-Rjp8z7DDYYDC4cVFrIkUPR34pj/view?usp=sharing)
and I also have some other chinese clients:
`CSO2Installer_Ver0.1_20150318
CSO2Installer_Ver0.5_20150403
CSO2Installer_Ver1.2_20150506
CSO2Installer_Ver3.0_20150902
CSO2Installer_Ver4.4_20151216
CSO2Installer_Ver7.2_20160912
CSO2Installer_Ver8.7_20170222
CSO2Installer_Ver8.8_20170308`
[PassCode is hf41]https://pan.baidu.com/s/1wAsdA23roNiyPuTRCByUfQ)
As far as I know the engine update of the chinese client is at the 20170705 version, and have a 2.85GB patch for old version but I cant find a way to download it.

**Comment by L-Leite** [comment]
thanks for the clients

**Comment by ADVABonnie** [comment]
@L-Leite  we understand your opinion but about the possibility that other versions of the game crashed on the new client and the old one did not but there are jambs in that version of the launcher

**Comment by ADVABonnie** [comment]
> @L-Leite @organnerx я надеюсь, что это может быть полезно для вас . Вот версия 20170510 китайского клиента, и 0.5.2 launcher хорошо работает
> [20170510](https://drive.google.com/file/d/16v5-_-Rjp8z7DDYYDC4cVFrIkUPR34pj/view?usp=sharing)
> а еще у меня есть несколько других китайских клиентов:
> CSO2Installer_Ver0.1_20150318
> CSO2Installer_Ver0.5_20150403
> CSO2Installer_Ver1.2_20150506
> CSO2Installer_Ver3. 0_20150902
> CSO2Installer_Ver4.4_20151216
> CSO2Installer_Ver7.2_20160912
> CSO2Installer_Ver8.7_20170222
> CSO2Installer_Ver8. 8_20170308
> [Код доступа - hf41](https://pan.baidu.com/s/1wAsdA23roNiyPuTRCByUfQ)
> Насколько я знаю, обновление двигателя китайского клиента находится в версии 20170705, и у меня есть патч 2.85 ГБ для старой версии, но я не могу найти способ загрузить его.

and you can re-upload all this to Google Drive

**Comment by ADVABonnie** [comment]
I will be able to test all versions of the game and find out where there is a full bypass for custom maps well, their inclusion shows with 0% loading

**Comment by KouKouChan** [comment]
> > @L-Leite @organnerx я надеюсь, что это может быть полезно для вас . Вот версия 20170510 китайского клиента, и 0.5.2 launcher хорошо работает
> > [20170510](https://drive.google.com/file/d/16v5-_-Rjp8z7DDYYDC4cVFrIkUPR34pj/view?usp=sharing)
> > а еще у меня есть несколько других китайских клиентов:
> > CSO2Installer_Ver0.1_20150318
> > CSO2Installer_Ver0.5_20150403
> > CSO2Installer_Ver1.2_20150506
> > CSO2Installer_Ver3. 0_20150902
> > CSO2Installer_Ver4.4_20151216
> > CSO2Installer_Ver7.2_20160912
> > CSO2Installer_Ver8.7_20170222
> > CSO2Installer_Ver8. 8_20170308
> > [Код доступа - hf41](https://pan.baidu.com/s/1wAsdA23roNiyPuTRCByUfQ)
> > Насколько я знаю, обновление двигателя китайского клиента находится в версии 20170705, и у меня есть патч 2.85 ГБ для старой версии, но я не могу найти способ загрузить его.
> 
> and you can re-upload all this to Google Drive

my Google Drive has only 15GB，I will try to upload 2 or 3 old clients

**Comment by KouKouChan** [comment]
CSO2Installer_Ver0.1_20150318
CSO2Installer_Ver1.2_20150506
CSO2Installer_Ver7.2_20160912
https://drive.google.com/file/d/1i4JnMSzpeFhGDKkIgt0PeXoaaPIabKlE/view?usp=sharing
https://drive.google.com/file/d/1Wu0Pu-dnLH0ZtP881-OrNapyDfkUZc8o/view?usp=sharing
https://drive.google.com/file/d/1QJpVAhl22RbLvZoRWnnkvow4Lp03wXf8/view?usp=sharing

**Comment by ADVABonnie** [comment]
thanks

**Comment by ADVABonnie** [comment]
since my server crashes I need to recreate it

**Comment by ADVABonnie** [comment]
> CSO2Installer_Ver0.1_20150318
> CSO2Installer_Ver1.2_20150506
> CSO2Installer_Ver7.2_20160912
> https://drive.google.com/file/d/1i4JnMSzpeFhGDKkIgt0PeXoaaPIabKlE/view?usp=sharing
> https://drive.google.com/file/d/1Wu0Pu-dnLH0ZtP881-OrNapyDfkUZc8o/view?usp=sharing
> https://drive.google.com/file/d/1QJpVAhl22RbLvZoRWnnkvow4Lp03wXf8/view?usp=sharing

Do you have a game from 2015 2014 and so on

**Comment by KouKouChan** [comment]
> > CSO2Installer_Ver0.1_20150318
> > CSO2Installer_Ver1.2_20150506
> > CSO2Installer_Ver7.2_20160912
> > https://drive.google.com/file/d/1i4JnMSzpeFhGDKkIgt0PeXoaaPIabKlE/view?usp=sharing
> > https://drive.google.com/file/d/1Wu0Pu-dnLH0ZtP881-OrNapyDfkUZc8o/view?usp=sharing
> > https://drive.google.com/file/d/1QJpVAhl22RbLvZoRWnnkvow4Lp03wXf8/view?usp=sharing
> 
> Do you have a game from 2015 2014 and so on just these 2016 builds

em, I think the first public beta chinese version by TianCity is CSO2Installer_Ver0.1_20150318.
but I have a 2014 korea version.

**Comment by ADVABonnie** [comment]
Thanks and in the Korean version there is also bigcity

**Comment by ADVABonnie** [comment]
the game started but 1 but the game froze when I went to the server and on your and on the other

**Comment by ADVABonnie** [comment]
> > > CSO2Installer_Ver0.1_20150318
> > > CSO2Installer_Ver1.2_20150506
> > > CSO2Installer_Ver7.2_20160912
> > > https://drive.google.com/file/d/1i4JnMSzpeFhGDKkIgt0PeXoaaPIabKlE/view?usp=sharing
> > > https://drive.google.com/file/d/1Wu0Pu-dnLH0ZtP881-OrNapyDfkUZc8o/view?usp=sharing
> > > https://drive.google.com/file/d/1QJpVAhl22RbLvZoRWnnkvow4Lp03wXf8/view?usp=sharing
> > 
> > 
> > У вас есть игра от 2015 2014 и так далее только эти сборки 2016 года
> 
> Эм, Я думаю, что первая публичная бета-версия китайской версии TianCity-это CSO2Installer_Ver0.1_20150318.
> но у меня есть корейская версия 2014 года.

you only had 1 version of the Korean game

**Comment by ADVABonnie** [comment]
> > > @L-Leite @organnerx я надеюсь, что это может быть полезно для вас . Вот версия 20170510 китайского клиента, и 0.5.2 launcher хорошо работает
> > > [20170510](https://drive.google.com/file/d/16v5-_-Rjp8z7DDYYDC4cVFrIkUPR34pj/view?usp=sharing)
> > > а еще у меня есть несколько других китайских клиентов:
> > > CSO2Installer_Ver0.1_20150318
> > > CSO2Installer_Ver0.5_20150403
> > > CSO2Installer_Ver1.2_20150506
> > > CSO2Installer_Ver3. 0_20150902
> > > CSO2Installer_Ver4.4_20151216
> > > CSO2Installer_Ver7.2_20160912
> > > CSO2Installer_Ver8.7_20170222
> > > CSO2Installer_Ver8. 8_20170308
> > > [Код доступа - hf41](https://pan.baidu.com/s/1wAsdA23roNiyPuTRCByUfQ)
> > > Насколько я знаю, обновление двигателя китайского клиента находится в версии 20170705, и у меня есть патч 2.85 ГБ для старой версии, но я не могу найти способ загрузить его.
> > 
> > 
> > и вы можете повторно загрузить все это на Google Диск
> 
> мой Google Диск имеет только 15 ГБ, я постараюсь загрузить 2 или 3 старых клиента

try deleting those versions and moving a couple more clients 
CSO2Installer_Ver0.1_20150318
CSO2Installer_Ver0.5_20150403
CSO2Installer_Ver1.2_20150506
CSO2Installer_Ver3. 0_20150902
CSO2Installer_Ver4.4_20151216

try to make these versions if I have already downloaded 1 of them you can not send them I will tell you what I download these CSO2Installer_Ver1.2_20150506
CSO2Installer_Ver7.2_20160912

**Comment by ADVABonnie** [comment]
@KouKouChan  we just need BigCity mode from 2014 
can you give me a 2014 build I get confused sometimes

**Comment by dounai2333** [comment]
> I will be able to test all versions of the game and find out where there is a full bypass for custom maps well, their inclusion shows with 0% loading

if you got stuck at 0%, that means your CS:S map version is mismatch with CSO2, bsp version of CS:S is 20, and CSO2 is 100.
you will need Notepad++ or Winhex etc to modify the map file to let the version matches, let's take an example, GMOD default map "gm_construct":
GMOD is also build on Source 2007, that means the bsp version is same as CS:S, open the gm_construct.bsp with Notepad++ or something (i'm using Ultraedit), you will see this:
![7{T%~F)5_IF86M 1I2EKPOK](https://user-images.githubusercontent.com/45044404/93660044-aa1b6700-fa7d-11ea-8a4e-42db749a9d97.png)
you may feel confused, but we only need to modify the beginning part:
![0NP9S1_S1K)P7D%71VCA2J9](https://user-images.githubusercontent.com/45044404/93660084-10a08500-fa7e-11ea-83ec-8d15acf63dcd.png)
(0x)14 means number 20 (hex to decimal), that is the bsp version of Source 2007, you just need to change the 14 to 64, save, and then CSO2 will read the map just as what you want to do (but i think it will still shows funny lump size)
then... nothing, i'm a lazy man so gl for testing :)

and yea, if you want mess other things up, also go test the map with Source 2013 (L4D2, CS:GO etc)
reference materials:
([hex to decimal](https://www.unitconverters.net/numbers/base-16-to-base-10.htm))
https://developer.valvesoftware.com/wiki/Source_BSP_File_Format
https://developer.valvesoftware.com/wiki/Lump_file_format

**Comment by 5SAYMON7** [comment]
> > I will be able to test all versions of the game and find out where there is a full bypass for custom maps well, their inclusion shows with 0% loading
> 
> if you got stuck at 0%, that means your CS:S map version is mismatch with CSO2, bsp version of CS:S is 20, and CSO2 is 100.
> you will need Notepad++ or Winhex etc to modify the map file to let the version matches, let's take an example, GMOD default map "gm_construct":
> GMOD is also build on Source 2007, that means the bsp version is same as CS:S, open the gm_construct.bsp with Notepad++ or something (i'm using Ultraedit), you will see this:
> ![7{T%~F)5_IF86M 1I2EKPOK](https://user-images.githubusercontent.com/45044404/93660044-aa1b6700-fa7d-11ea-8a4e-42db749a9d97.png)
> you may feel confused, but we only need to modify the beginning part:
> ![0NP9S1_S1K)P7D%71VCA2J9](https://user-images.githubusercontent.com/45044404/93660084-10a08500-fa7e-11ea-83ec-8d15acf63dcd.png)
> (0x)14 means number 20 (hex to decimal), that is the bsp version of Source 2007, you just need to change the 14 to 64, save, and then CSO2 will read the map just as what you want to do (but i think it will still shows funny lump size)
> then... nothing, i'm a lazy man so gl for testing :)
> 
> and yea, if you want mess other things up, also go test the map with Source 2013 (L4D2, CS:GO etc)
> reference materials:
> ([hex to decimal](https://www.unitconverters.net/numbers/base-16-to-base-10.htm))
> https://developer.valvesoftware.com/wiki/Source_BSP_File_Format
> https://developer.valvesoftware.com/wiki/Lump_file_format

CSO2 start load map, but after load - game crash

**Comment by ADVABonnie** [comment]
We'd rather wait for the map Converter

**Comment by ADVABonnie** [comment]
but we need the 2014 version the Korean version as we love BigCity mode

**Comment by KouKouChan** [comment]
I will upload 2014 korea client later , and you should be sure that have downloaded CSO2Installer_Ver7.2_20160912 ， I will delete this file because my GoogleDrive has only 2GB free space.

**Comment by ADVABonnie** [comment]
Thanks

**Comment by ADVABonnie** [comment]
@KouKouChan CSO2Installer_Ver7.2_20160912 I have

**Comment by organnerx** [comment]
@KouKouChan can you please upload *all clients that you have* to dropmefiles.com? It allows to upload multiple files at the time up to 50gb, it means you can upload all clients that you have and get 1 link instead of multiple links. Just be sure to set an expiration date to 14 days instead of 7 days

**Comment by KouKouChan** [comment]
> dropmefiles

ok, i will try.

**Comment by KouKouChan** [comment]
20140528 korea version 
https://drive.google.com/file/d/17EPjFR2sjDORTwWDO4l0QcFZ_VLx99YN/view?usp=sharing

**Comment by ADVABonnie** [comment]
thanks

**Comment by ADVABonnie** [comment]
I can run the game version but I can't connect to the servers

@L-Leite can you make us a server to run the 2014 version

**Comment by ADVABonnie** [comment]
![Аннотация 2020-09-21 163602](https://user-images.githubusercontent.com/69756761/93773312-a841d700-fc28-11ea-8fdf-f9c23d613d6e.jpg)

**Comment by ADVABonnie** [comment]
Oh haven't heard anything rumored about the Maps conversion Converter

**Comment by organnerx** [comment]
Conversion tool is still needed. Bump :)

**Comment by ADVABonnie** [comment]
> 20140528 Korea
> версия https://drive.google.com/file/d/17EPjFR2sjDORTwWDO4l0QcFZ_VLx99YN/view?usp=sharing

Could you please give me this Link again from the game version please

**Comment by KouKouChan** [comment]
> > 20140528 Korea
> > версия https://drive.google.com/file/d/17EPjFR2sjDORTwWDO4l0QcFZ_VLx99YN/view?usp=sharing
> 
> Could you please give me this Link again from the game version please

did you lost the file?

**Comment by ADVABonnie** [comment]
> > > 20140528 Korea
> > > версия https://drive.google.com/file/d/17EPjFR2sjDORTwWDO4l0QcFZ_VLx99YN/view?usp=sharing
> > 
> > 
> > Could you please give me this Link again from the game version please
> 
> did you lost the file?

yes I just got a new computer and there was an error in my laptop, which is why I had to reinstall the system there

**Comment by ADVABonnie** [comment]
@KouKouChan

**Comment by ADVABonnie** [comment]
@KouKouChan Are you here

**Comment by KouKouChan** [comment]
> @KouKouChan Are you here

wait 2 or 3 days, I'm not in home >_<

**Comment by ADVABonnie** [comment]
Damn it is clear So it was necessary to warn

**Comment by ADVABonnie** [comment]
> > @KouKouChan Are you here
> 
> wait 2 or 3 days, I'm not in home >_<

Well, if you are at home then write here ADVABonnie#1923

**Comment by KouKouChan** [comment]
> > > @KouKouChan Are you here
> > 
> > 
> > wait 2 or 3 days, I'm not in home >_<
> 
> Well, if you are at home then write here ADVABonnie#1923

tonight, trust me

**Comment by ADVABonnie** [comment]
OK

**Comment by KouKouChan** [comment]
> OK

https://drive.google.com/file/d/1w6zARagJ3sgY7s3gPMyIwMJ_c_ecurjQ/view?usp=sharing

**Comment by ADVABonnie** [comment]
Thank you

**Comment by BKVad1m** [comment]
> > OK
> 
> https://drive.google.com/file/d/1w6zARagJ3sgY7s3gPMyIwMJ_c_ecurjQ/view?usp=sharing

files was deleted

**Comment by BKVad1m** [comment]
@KouKouChan reupload please to make map
