### ISSUE TITLE
It is possible to "remove" the CSO2 Crosshair and use the CS:S instead?

### ISSUE THREAD

**Issue by Valen7789** [L-Leite/cso2-launcher#91]
I know that deactivating the cso2 hud with the cvar "cso2_hud 0" activates the CS:S hud and through the console you can enter CS:S crosshair commands and customize it from there. My question is, can ONLY the CSO2 crosshair be disabled and the CS:S one be kept?

**Comment by L-Leite** [comment]
i don't know any way of doing this. i think you would have to patch the game
