### ISSUE TITLE
GFX console?

### ISSUE THREAD

**Issue by organnerx** [L-Leite/cso2-launcher#94]
@L-Leite hello. I see that you have implemented Source console. That's nice.
I want to point out that there is already a CSO2 console in game built in GFX file. It is also fully designed and animated. Have you tested it? Does it even work or it was not used by Nexon? I think it can be opened by modifying GFX file or by patching the engine. You can take a look at it if you want to.
Screenshot of GFX: usually scripts that starts with "CSO..." are related to old UI. And there are 2 of them. So I think the console was created for old UI (CSOConsoleApp) and for new UI (systemConsoleApp).
![unknown](https://user-images.githubusercontent.com/45734900/93971572-290fe880-fd79-11ea-8169-beecb78a75c9.png)

**Comment by L-Leite** [comment]
CSOConsole is a debug console for the scaleform UI, it allows you test and profile some UI components with it
you can enable it by editing the P-Code of CSO2UI::setupUI with JPEXS decompiler: move the call to `this.uiConsole.fnConsoleOpen();` out of the `if(Extensions.isGFxPlayer)` statement
it looks like this:
![screenshot](https://user-images.githubusercontent.com/4953934/93979229-f95ee180-fd74-11ea-847b-bfc7be08f858.png)

**Comment by ADVABonnie** [comment]
@L-Leite I think this console is perfectly included in the game

**Comment by Valen7789** [comment]
@L-Leite First of all, a million thanks for getting this version of the console working. very comfortable and beautiful for my eyes. already leaving the compliments.
seeing what @organnerx posted, would there be the possibility of "converting" the Source console using ScaleformUI? I say this as a possibility to fix the problem that the console is under the UI of CSO2
![20200923033720_1](https://user-images.githubusercontent.com/58377169/93985786-e8ee3d00-fd5b-11ea-8dea-22d035de1f7c.jpg)

**Comment by organnerx** [comment]
@Valen7789 I do not think it will worth the amount of time spent on creating a complex thing like this one. It requires both GFX editing and game patching, a really hard thing to do.
@L-Leite Thanks for showing us how that UI console looks like

**Comment by ADVABonnie** [comment]
> CSOConsole is a debug console for the scaleform UI, it allows you test and profile some UI components with it
> you can enable it by editing the P-Code of CSO2UI::setupUI with JPEXS decompiler: move the call to out of the statement
> it looks like this:`this.uiConsole.fnConsoleOpen();``if(Extensions.isGFxPlayer)`
> ![screenshot](https://user-images.githubusercontent.com/4953934/93979229-f95ee180-fd74-11ea-847b-bfc7be08f858.png)

And how do I need to enable it if I just changed it 0
