### ISSUE TITLE
old version 2014 to 2013 

### ISSUE THREAD

**Issue by ADVABonnie** [L-Leite/cso2-launcher#96]
Luís Leite Hello there is 1 problem or rather 2 problems can you make a launcher for the 2014 and 2013 versions and a server for viewing custom maps if you have the opportunity you will see and write to us We look forward to hearing from you do everything without bugs and the server is also only with Node.js without errors and bugs 
![splash_000](https://user-images.githubusercontent.com/69756761/94876605-d4e3c300-0460-11eb-95b9-27b7f4d7f3fa.jpg)

**Comment by ADVABonnie** [comment]
@L-Leite I can give you the 2014 version for the big city test

**Comment by ADVABonnie** [comment]
https://drive.google.com/file/d/17EPjFR2sjDORTwWDO4l0QcFZ_VLx99YN/view?usp=sharing

**Comment by L-Leite** [comment]
i don't plan on supporting old version of cso2
