### ISSUE TITLE
custom interfaces from 2018 to 2017

### ISSUE THREAD

**Issue by ADVABonnie** [L-Leite/cso2-launcher#97]
@L-Leite Hi Compertum est, quod ego potest mutare dapibus 2017, et in veteri 2018 dapibus est an bene ut reponat
![cso2_0360](https://user-images.githubusercontent.com/69756761/95034917-01e7de00-06cc-11eb-963c-1d4b25950c54.jpg)

**Comment by ADVABonnie** [comment]
Interface New 2018 Old Interface 2017 Old Game 2017 New Interface 2018

**Comment by L-Leite** [comment]
you can try replacing the files in ui_gfx

**Comment by ADVABonnie** [comment]
> 

Yes only 1 function does not work
![cso2_0358](https://user-images.githubusercontent.com/69756761/95150698-746ec180-0791-11eb-8a61-59e0028f81a6.jpg)
I do not know how to do this so that the cases are displayed
or remove this function and return a new one

**Comment by L-Leite** [comment]
cases aren't implemented in master server yet

**Comment by ADVABonnie** [comment]
I play on the EU/RU server and this function doesn't work here
